version: "3"
name: "vhm-tools"
services:
  postgres:
    image: postgres:14
    container_name: pg_tools
    ports:
      - 2340:5432
    environment:
      POSTGRES_USER: vhm_tools
      POSTGRES_PASSWORD: vhm_tools
      POSTGRES_DB: vhm_tools
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'vhm_tools']
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis_tools
    ports:
      - 9730:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 30s
    volumes:
      - redis_data:/var/lib/redis/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_tools
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: vhm_tools
      RABBITMQ_DEFAULT_PASS: vhm_tools
    healthcheck:
      test: ["CMD", "rabbitmqctl", "ping"]
      interval: 30s # Health check interval
      timeout: 15s # Health check timeout
      retries: 3 # Number of retries before considering the container unhealthy

networks:
  default:
    name: vhm-tools-nw
    external: true

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local
